// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {queue} from '../models';
import {context} from '../models';
import {config} from '../models';
import {ffmpeg} from '../models';
import {models} from '../models';
import {system} from '../models';

export function AddTask(arg1:main.CreateTaskRequest):Promise<queue.Task>;

export function CancelModelDownload(arg1:string):Promise<void>;

export function CancelTask(arg1:string):Promise<void>;

export function CheckModelReady(arg1:string,arg2:boolean):Promise<boolean|string>;

export function CheckPath(arg1:string):Promise<Record<string, any>>;

export function ClearAllTasks():Promise<void>;

export function ClearCanceledTasks():Promise<void>;

export function ClearCompletedTasks():Promise<void>;

export function ConfirmQuit():Promise<void>;

export function DeleteModel(arg1:string,arg2:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function DownloadAllModels(arg1:string):Promise<void>;

export function DownloadModel(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function EmitLog(arg1:string,arg2:string):Promise<void>;

export function EmitQueueUpdated(arg1:Array<queue.Task>):Promise<void>;

export function EmitTaskUpdated(arg1:queue.Task):Promise<void>;

export function ExecuteTask(arg1:context.Context,arg2:queue.Task,arg3:config.AppConfig,arg4:any):Promise<void>;

export function GetAvailableEncoders():Promise<Array<ffmpeg.EncoderInfo>>;

export function GetConfig():Promise<config.AppConfig>;

export function GetModelConfig():Promise<models.ModelConfig>;

export function GetModelList():Promise<Array<models.ModelItem>>;

export function GetSystemInfo():Promise<system.SystemInfo>;

export function GetSystemUsage():Promise<system.SystemUsage>;

export function GetTasks():Promise<Array<queue.Task>>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function PauseTask(arg1:string):Promise<void>;

export function ProbeMedia(arg1:string):Promise<ffmpeg.MediaInfo>;

export function RefreshAvailableEncoders():Promise<Array<ffmpeg.EncoderInfo>>;

export function ResumeTask(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:Array<main.DialogFilter>):Promise<string>;

export function SelectMultipleFiles(arg1:string,arg2:Array<main.DialogFilter>):Promise<Array<string>>;

export function SelectSaveFile(arg1:string,arg2:string,arg3:main.DialogFilter):Promise<string>;

export function SetSelectedMirror(arg1:string):Promise<void>;

export function SwitchGlobalVariant(arg1:string):Promise<void>;

export function SwitchModelVariant(arg1:string,arg2:string):Promise<void>;
