// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['main']['App']['AddTask'](arg1);
}

export function CancelModelDownload(arg1) {
  return window['go']['main']['App']['CancelModelDownload'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function CheckModelReady(arg1, arg2) {
  return window['go']['main']['App']['CheckModelReady'](arg1, arg2);
}

export function CheckPath(arg1) {
  return window['go']['main']['App']['CheckPath'](arg1);
}

export function ClearAllTasks() {
  return window['go']['main']['App']['ClearAllTasks']();
}

export function ClearCanceledTasks() {
  return window['go']['main']['App']['ClearCanceledTasks']();
}

export function ClearCompletedTasks() {
  return window['go']['main']['App']['ClearCompletedTasks']();
}

export function ConfirmQuit() {
  return window['go']['main']['App']['ConfirmQuit']();
}

export function DeleteModel(arg1, arg2) {
  return window['go']['main']['App']['DeleteModel'](arg1, arg2);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DownloadAllModels(arg1) {
  return window['go']['main']['App']['DownloadAllModels'](arg1);
}

export function DownloadModel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadModel'](arg1, arg2, arg3, arg4);
}

export function EmitLog(arg1, arg2) {
  return window['go']['main']['App']['EmitLog'](arg1, arg2);
}

export function EmitQueueUpdated(arg1) {
  return window['go']['main']['App']['EmitQueueUpdated'](arg1);
}

export function EmitTaskUpdated(arg1) {
  return window['go']['main']['App']['EmitTaskUpdated'](arg1);
}

export function ExecuteTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteTask'](arg1, arg2, arg3, arg4);
}

export function GetAvailableEncoders() {
  return window['go']['main']['App']['GetAvailableEncoders']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetModelConfig() {
  return window['go']['main']['App']['GetModelConfig']();
}

export function GetModelList() {
  return window['go']['main']['App']['GetModelList']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetSystemUsage() {
  return window['go']['main']['App']['GetSystemUsage']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function PauseTask(arg1) {
  return window['go']['main']['App']['PauseTask'](arg1);
}

export function ProbeMedia(arg1) {
  return window['go']['main']['App']['ProbeMedia'](arg1);
}

export function RefreshAvailableEncoders() {
  return window['go']['main']['App']['RefreshAvailableEncoders']();
}

export function ResumeTask(arg1) {
  return window['go']['main']['App']['ResumeTask'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}

export function SelectMultipleFiles(arg1, arg2) {
  return window['go']['main']['App']['SelectMultipleFiles'](arg1, arg2);
}

export function SelectSaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectSaveFile'](arg1, arg2, arg3);
}

export function SetSelectedMirror(arg1) {
  return window['go']['main']['App']['SetSelectedMirror'](arg1);
}

export function SwitchGlobalVariant(arg1) {
  return window['go']['main']['App']['SwitchGlobalVariant'](arg1);
}

export function SwitchModelVariant(arg1, arg2) {
  return window['go']['main']['App']['SwitchModelVariant'](arg1, arg2);
}
